services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:nievedelimon@db:5432/Laboratorio3
    volumes:
      - ./backend/app:/app/app
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_BASE_URL: "http://backend:8000"
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nievedelimon
      POSTGRES_DB: Laboratorio3
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Laboratorio3"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: